const classesData = {
    classesFund: [
     { class: "Matemática",
        pdf: "https://drive.google.com/u/0/uc?id=1xog7al6WIlqOdfGP3acD7oY7pLaAVAvV&export=download",
        testLink: '/',
    }, {
        class: "Lingua Portuguesa",
        pdf :"https://drive.google.com/u/0/uc?id=1QP8aqhNuNtWWn5JnN4_SNCilXzhLG7B0&export=download",
        testLink: '/',
    },
    {
        class: "História e Geografia",
        pdf : "https://drive.google.com/u/0/uc?id=1UGTzItcToU-hdHL3eafLJN_q65c6mQaF&export=download",
        testLink: '/',
    },
    { class: "Ciências",
      pdf : "https://drive.google.com/u/0/uc?id=1nuowAkabqpbH10WP9GJ5HSUUFAOeOBqB&export=download",
      testLink: '/',
    }

    ],
    CienciasFundTeste1: [
        {
            question: "Para alguns filósofos gregos da Antiguidade, enxergamos as coisas à nossa volta porque nossos olhos emitem partículas que, ao atingirem os objetos, permitem que sejam vistos. Atualmente, entendemos que os objetos podem ser vistos porque a luz que eles emitem ou refletem atinge os nossos olhos, sensibilizando-os.",
            questionPart2: "Uma maneira de mostrar que a hipótese dos gregos estava errada é tentar ler um livro impresso",
            A: "de olhos fechados.",
            B: 'virando as costas para ele.',
            C: "colocado atrás de uma parede.",
            D: "em uma sala sem luz.",
            name: 'option1',
            position: '1°',
        },
        {
            question: "Pamonha é um dos deliciosos pratos típicos dos estados de Goiás e Minas Gerais. A verdadeira pamonha é feita à base de milho verde e leite, acrescidos de sal ou açúcar, queijo ou linguiça, e cozida na palha do milho. Antigamente a pamonha só existia numa época do ano, pois só se semeava e colhia o milho na estação chuvosa. Desde os anos 1970, goianos e mineiros podem se deliciar com pamonhas o ano todo, devido a uma nova tecnologia.",
            questionPart2: "A inovação tecnológica que possibilitou a expansão do período de plantio foi a",
            A: "irrigação.",
            B: 'aração mecânica.',
            C: "adubação química.",
            D: "colheita mecanizada.",
            name: 'option2',
            position: '2°',
        },
        {
            question: "A figura ilustra duas boias acopladas a braços articulados numa usina de ondas para geração de eletricidade",
            questionPart2: "A energia elétrica produzida nessa usina é convertida a partir do(a)",
            A: "calor da água.",
            B: 'densidade da boia.',
            C: "movimento da água.",
            D: "temperatura da boia.",
            name: 'option3',
            position: '3°',
            img: "/CienciaFundProva1/Questão3.png",
        },
        {
            question: "Entre os alimentos que possuem propriedades funcionais estão incluídos aqueles que contêm probióticos, como os lactobacilos vivos.",
            questionPart2: "A ação desses microrganismos é de",
            A: "inibir a flora intestinal.",
            B: 'eliminar a flora intestinal.',
            C: "equilibrar a flora intestinal.",
            D: "substituir a flora intestinal.",
            name: 'option4',
            position: '4°',
          
        },
        {
            question: "Em 1798, o inglês Edward Jenner publicou, em livro, os resultados de seus experimentos, demonstrando que inocular o líquido do pus das feridas da varíola bovina — doença muito branda em seres humanos — em uma pessoa normal e sadia protegia essa pessoa contra a varíola humana. Trata-se de um método eficaz que foi concebido para prevenir uma doença infecciosa.",
            questionPart2: "A qual importante descoberta o cientista chegou com seus experimentos?",
            A: "Soro",
            B: 'Vacina',
            C: "Anestesia",
            D: "Antibiótico",
            name: 'option5',
            position: '5°',
            
        },
        {
            question: "O aluguel de patinetes nas grandes cidades tem sido frequente, principalmente nos locais onde o trânsito de veículos é bastante intenso. Os patinetes possuem duas rodas, são movidos a eletricidade e esse serviço pode ser acessado por meio de aplicativos nos smartphones.",
            questionPart2: "Um argumento favorável ao uso desse meio de transporte é que ele",
            A: "diminui os riscos de acidentes de trânsito.",
            B: 'é mais ágil em longas distâncias.',
            C: "traz segurança aos pedestres.",
            D: "agiliza a mobilidade urbana.",
            name: 'option6',
            position: '6°',
            
        },
        {
            question: "O Cerrado tipicamente apresenta uma estação chuvosa e uma estação seca que se alternam. Essa condição climática compromete o abastecimento hídrico durante a estação seca, influenciando diretamente a vegetação presente nesse bioma. As árvores, por exemplo, possuem certas características adaptativas para essa condição sem as quais não sobreviveriam.",
            questionPart2: "Uma dessas características é o(a)",
            A: "folha larga.",
            B: 'flor colorida.',
            C: "raiz profunda.",
            D: "fruto suculento.",
            name: 'option7',
            position: '7°',
        
        },
        {
            question: "A decomposição da biomassa presente em aterros sanitários produz um combustível, ainda pouco aproveitado, que pode ser queimado para a produção de energia.",
            questionPart2:"Esse combustível é o",
            A: "etanol.",
            B: 'metano.',
            C: "petróleo.",
            D: "hidrogênio.",
            name: 'option8',
            position: '8°',
            
        },
        {
            question: "Sobras de alimentos são resíduos orgânicos compostos por material biológico e, por isso, ricos em nutrientes que podem retornar para a natureza, completando o ciclo da matéria. Essa ciclagem pode ser feita até mesmo em casa, pelo processo de compostagem, e o produto gerado por essa técnica pode ser utilizado como adubo em hortas caseiras.",
            questionPart2: " A utilização desse adubo fortalece as plantas porque",
            A: "fornece elementos químicos para o desenvolvimento da planta.",
            B: 'é utilizado como fonte de energia de que a planta precisa para crescer.',
            C: "reduz o calor no solo e diminui a perda de água pelas plantas.",
            D: "atrai minhocas que protegem a planta.",
            name: 'option9',
            position: '9°',
        },
        {
            question: "Às margens do Rio São Francisco, na cidade de Cabrobó, no sertão pernambucano, desenvolve-se um processo de desertificação. Na área, o arroz era cultivado há cerca de 20 anos através da técnica de irrigação por inundação.",
            questionPart2: "A técnica contribuiu para o desenvolvimento do problema porque causou o(a)",
            A: "contaminação do solo devido aos metais pesados carregados pelo rio.",
            B: 'contaminação do solo devido à diluição de agrotóxicos nas áreas alagadas.',
            C: "aumento da salinidade do solo devido à deposição de compostos diluídos na água utilizada.",
            D: "aumento da alcalinidade do solo devido à decomposição de matéria orgânica nas áreas inundadas.",
            name: 'option10',
            position: '10°',
        },
        {
            question: "O gráfico apresenta dados do Instituto Brasileiro de Geografia e Estatística (IBGE), referentes às taxas de sobrepeso (excesso de peso) e de obesidade em meninos e meninas nas diversas regiões do Brasil, em 2016.",
            questionPart2: "Na análise dos dados, verifica-se menor variação nas taxas de sobrepeso (excesso de peso) e obesidade entre meninos e meninas na Região",
            A: "Nordeste.",
            B: 'Centro-Oeste.',
            C: "Sudeste.",
            D: "Sul.",
            name: 'option11',
            position: '11°',
            img: "/CienciaFundProva1/Questão11.png",
        },
        {
            question: "Em algumas cidades, durante o período da seca, o que se sente é um calor intenso durante os dias e nenhuma previsão de chuva. Nessas condições é melhor ter cuidado, principalmente quando a umidade do ar está abaixo dos 60%.",
            questionPart2: "Nessas condições climáticas, a recomendação é",
            A: "usar ventiladores.",
            B: 'manter a residência fechada.',
            C: "aumentar a ingestão de água.",
            D: "praticar exercícios no período do almoço.",
            name: 'option12',
            position: '12°',
        },
        {
            question: "O excesso de exposição solar causa doenças na pele que se desenvolvem devido aos danos que a radiação ultravioleta causa ao DNA dessas células. No Brasil, verifica-se um aumento da mortalidade decorrente desse tipo de exposição solar.",
            questionPart2: "Essa exposição excessiva pode induzir na pele o surgimento de",
            A: "vitiligo.",
            B: 'câncer.',
            C: "verruga.",
            D: "brotoeja.",
            name: 'option13',
            position: '13°', 
        },

        {
            question: "Uma pessoa deseja levantar um bloco que se encontra parado e apoiado numa superfície plana e horizontal, como ilustram as figuras.",
            questionPart2: "Em qual situação a pessoa faz mais força para levantar o bloco?",
            A: "1",
            B: '2',
            C: "3",
            D: "4",
            name: 'option14',
            position: '14°',
            img: "/CienciaFundProva1/Questão14.png",
        },
        {
            question: "A silicose é uma doença relacionada a determinadas profissões, como a mineração de granito e a construção civil, entre outras, que envolvem o manuseio de pó de sílica. A consequência da falta de cuidados nesse manuseio é o aparecimento de doenças pulmonares nos trabalhadores, em função da inalação frequente do pó.",
            questionPart2: "O trabalhador que entrar em contato com o pó de sílica durante muitos anos poderá desenvolver essa doença, que afetará diretamente o sistema",
            A: "excretor.",
            B: 'circulatório.',
            C: "respiratório.",
            D: "digestório.",
            name: 'option15',
            position: '15°',
            
        },
        {
            question: "A automedicação é uma das modalidades mais comuns do uso inadequado de medicamentos. Contudo, tal prática oferece diversos riscos à saúde. Um desses riscos está associado à proliferação, no organismo da pessoa que se automedica, de bactérias resistentes, capazes de causar infecções de difícil tratamento.",
            questionPart2: "O risco mencionado diz respeito, especificamente, à utilização por conta própria de qual tipo de medicamento?",
            A: "Anticoagulantes",
            B: 'Antitérmicos',
            C: "Analgésicos",
            D: "Antibióticos",
            name: 'option16',
            position: '16°',
           
        },
        {
            question: "A pirâmide apresenta recomendações sobre a prática de atividades físicas para manutenção da saúde e da boa forma corporal.",
            questionPart2: "De acordo com a pirâmide, as atividades físicas recomendadas com maior frequência semanal são atividades como",
            A: "correr e jogar bola.",
            B: 'descansar e relaxar.',
            C: "caminhar e subir escadas.",
            D: "levantar pesos e se alongar.",
            name: 'option17',
            position: '17°',
            img: "/CienciaFundProva1/Questão17.png",
        },
        {
            question: "O planejamento familiar, ou seja, o número de filhos que o casal deseja ter, pode ser feito com o uso de diversos métodos anticoncepcionais.",
            questionPart2: "O método que, além de atender ao planejamento citado, também contribui para evitar doenças sexualmente transmissíveis é o(a)",
            A: "pílula anticoncepcional.",
            B: 'dispositivo intrauterino.',
            C: "preservativo.",
            D: "diafragma.",
            name: 'option18',
            position: '18°',
            
        },
        {
            question: "A Organização Mundial da Saúde estima que 1,9 bilhão de adultos tenham sobrepeso, sendo 600 milhões com obesidade. Ainda assim, de acordo com estudos publicados, nos últimos 30 anos nenhum país conseguiu elaborar estratégias para reverter a epidemia de obesidade de forma consistente.",
            questionPart2: "As estratégias para reverter essa epidemia necessariamente devem envolver",
            A: "social.",
            B: 'regional.',
            C: "etária.",
            D: "profissional.",
            name: 'option19',
            position: '19°',
           
        },
        {
            question: "",
            questionPart2: "Para melhorar o funcionamento do intestino, diminuindo a chance de prisão de ventre, uma pessoa deverá escolher preferencialmente o alimento ",
            A: "I, pois ele apresenta a maior quantidade de sódio.",
            B: 'II, pois ele apresenta a maior quantidade de fibra alimentar.',
            C: "III, pois ele apresenta a menor quantidade de proteínas.",
            D: "IV, pois ele apresenta a menor quantidade de carboidratos.",
            name: 'option20',
            position: '20°',
            img: "/CienciaFundProva1/Questão20.png",
        },
        {
            question: "Enquanto colava o vidro de um aquário com adesivo à base de silicone, um senhor deixou derramar um pouco desse adesivo sobre a mesa. Ao tentar limpar a mesa com um pano umedecido em água, ele reparou que o silicone se espalhou ainda mais.",
            questionPart2: "O material adequado para remover esta substância é o",
            A: "óleo.",
            B: 'etanol.',
            C: "vinagre.",
            D: "refrigerante.",
            name: 'option21',
            position: '21°',
           
        },
        {
            question: "",
            questionPart2: "Esse mito ignora o fato de que os raios se direcionam, preferencialmente, para objetos de",
            A: "concreto em áreas descampadas.",
            B: 'plástico em ambientes aquáticos.',
            C: "vidro temperado em janelas.",
            D: "metal em pontos mais altos.",
            name: 'option22',
            position: '22°',
            img: "/CienciaFundProva1/Questão22.png",
        },
        {
            question: "O uso de cisternas para promover o acesso universal à água na zona rural, em especial no semiárido brasileiro, é uma etapa fundamental para a superação da extrema pobreza na região. No entanto, o mau uso desses dispositivos foi apontado como uma das causas do aumento da quantidade de casos de dengue em São Sebastião (Alagoas). O município, que possui uma população rural superior à urbana, foi listado em 2015 pela Secretaria Estadual de Saúde entre as cidades com epidemia dessa doença.",
            questionPart2: "Que medida deve ser tomada para manter a água potável e evitar outra epidemia? ",
            A: "Colocar larvicidas nas cisternas.",
            B: 'Manter bem vedadas as cisternas.',
            C: "Ferver a água proveniente das cisternas.",
            D: "Instalar uma lâmpada simples, à noite, próximo às cisternas.",
            name: 'option23',
            position: '23°',
            
        },
        {
            question: "",
            questionPart2: "A atitude apresentada colabora para enfrentar um problema que afeta as sociedades atuais associado ao(à)",
            A: "poluição do ambiente urbano.",
            B: 'desperdício de recursos da natureza.',
            C: "envelhecimento rápido de tecnologias.",
            D: "diminuição da prática de atividades físicas.",
            name: 'option24',
            position: '24°',
            img: "/CienciaFundProva1/Questão24.png",
        },
        {
            question: "Em uma noite, Vênus e Júpiter protagonizaram um fenômeno de conjunção de planetas. Isso significa que os astros se alinharam para formar um ponto brilhante duplo visível a partir da Terra.",
            questionPart2: "As posições dos três planetas na conjunção descrita no texto estão representadas em:",
            A: "",
            B: '',
            C: "",
            D: "",
            name: 'option25',
            position: '25°',
            img: "/CienciaFundProva1/Questão25.png",
        }, {
            question: "Após o nascer do Sol no leste, um observador percebeu que as sombras de uma haste projetadas no solo mudavam de tamanho e posição ao longo do dia, conforme ilustra a figura. A posição dos pontos cardeais está ilustrada na rosa dos ventos.",
            questionPart2: "Qual sombra corresponde ao horário mais próximo do amanhecer?",
            A: "1",
            B: '2',
            C: "3",
            D: "4",
            name: 'option26',
            position: '26°',
            img: "/CienciaFundProva1/Questão26.png",
        },
        {
            question: "Ao aquecer água numa chaleira até aproximadamente 80 °C, as moléculas começam a vibrar e a se movimentar mais rapidamente, fazendo com que a água passe a ocupar mais espaço, mas sem evaporar.",
            questionPart2: "A figura que melhor representa o fenômeno descrito é:",
            A: "",
            B: '',
            C: "",
            D: "",
            name: 'option27',
            position: '27°',
            img: "/CienciaFundProva1/Questão27.png",
        },
        {
            question: "A capacidade de observação e a criatividade humana permitiram, ao longo dos séculos, a descoberta e a transformação de diversas substâncias encontradas na natureza que servem às tecnologias da nossa sociedade e que são fontes renováveis. Um exemplo é a borracha, que é obtida a partir do látex vindo de uma árvore, a seringueira.",
            questionPart2: "Para obtenção da matéria-prima desse produto, extrai-se o(a)",
            A: "seiva.",
            B: 'lenho.',
            C: "folha.",
            D: "raiz.",
            name: 'option28',
            position: '28°',
    
        },
        {
            question: "Em algumas localidades não existem estações de tratamento de água e esgoto (ETAs) e, portanto, os esgotos domésticos não tratados são jogados diretamente nos rios. Como a água segue suja para os cursos-d’água, isso compromete a qualidade da água para os diversos usos, inclusive para a agricultura.",
            questionPart2: "Uma solução para os moradores que vivem nessas localidades é",
            A: "usar diretamente os esgotos como adubo.",
            B: 'enterrar esses esgotos no fundo dos quintais.',
            C: "misturar os esgotos na ração para os animais.",
            D: "direcionar os esgotos para tanques ou fossas sépticas.",
            name: 'option29',
            position: '29°',
            
        },
        {
            question: "O Brasil possui um grande potencial para gerar eletricidade a partir da energia solar. Só para se ter uma ideia, no local menos ensolarado do Brasil é possível gerar mais eletricidade solar do que no local mais ensolarado da Alemanha, que é um dos líderes no uso desse tipo de energia no mundo. A figura apresenta a intensidade da incidência de radiação solar no território brasileiro.",
            questionPart2: "Em qual local indicado no mapa tem-se um maior potencial para gerar eletricidade a partir da energia solar?",
            A: "1",
            B: '2',
            C: "3",
            D: "4",
            name: 'option30',
            position: '30°',
            img: "/CienciaFundProva1/Questão30.png",
        },
    ],
    matematicaFundTeste2: [
        {
            question: "Uma criança, viajando de carro com o pai, pergunta como se lê o número “200” junto com a letra “m” na placa que se observa na figura.",
            questionPart2: "Com base nas informações da placa, o pai responde que “200” e “m”, juntos, querem dizer",
            A: "duzentos miligramas.",
            B: 'duzentos metros.',
            C: "duzentos milímetros.",
            D: "duzentos minutos.",
            name: 'option1',
            position: '1°',
            img: "/MathFundProva2/Questão1.png",
        },
        {
            question: "O edital de um processo seletivo abre 30 vagas para diversos cargos. Encerradas as inscrições, a razão candidato/vaga era de 28 por 1. Para a aplicação das provas, serão utilizadas salas de  aula nas quais as carteiras serão etiquetadas com os nomes dos candidatos. Foi definido pela  comissão organizadora que cada sala precisa ter exatamente 56 carteiras, contando que todos os candidatos estejam presentes para fazer a prova. Pretende-se que a escola mais adequada  a esse propósito tenha o menor número de salas, compatível com a exigência dessa comissão.   Para isso, a comissão organizadora dispõe de uma tabela com quatro escolas, as quais possuem o número desejado de carteiras por sala.",
            questionPart2:"A escola escolhida pela comissão organizadora será a" ,
            A: "I.",
            B: 'II.',
            C: "III.",
            D: "IV.",
            name: 'option2',
            position: '2°',
            img: "/MathFundProva2/Questão2.png",
        },
        {
            question: "Um pedreiro precisa pavimentar, comlajotas quadradas, todo o piso de uma sala.Ele desenhou a vista superior da sala em umpapel quadriculado, no qual cada quadradinhoda malha representa uma lajota, como mostraa figura.",
            questionPart2 : "A loja onde ele irá comprar as lajotas vendeapenas lajotas inteiras, cabendo ao pedreirorecortá-las depois. Além disso, devido aorisco de quebra durante a obra, esse pedreirocomprará 2 peças a mais do que a quantidadenecessária para a pavimentação da sala.Qual a quantidade mínima de lajotas que opedreiro deve comprar?",
            A: "18",
            B: '19',
            C: "21",
            D: "23",
            name: 'option3',
            position: '3°',
            img: "/MathFundProva2/Questão3.png",
        },
        {
            question: "Artur recebe R$ 2 000,00 de salário mensal decidiu agendar uma reunião com seu chefepara negociar um reajuste salarial.",
            questionPart2: "O índice mínimo de reajuste que ele devenegociar para que seu salário passe a ser, nomínimo, de R$ 2 500,00 é", 
            A: "20%",
            B: '25%',
            C: "50%",
            D: "125%",
            name: 'option4',
            position: '4°'
        },
        {
            question: "Uma colcha de retalhos, com formatoretangular, é feita com quatro recortestriangulares de tecidos, conforme a figura.",
            questionPart2: "Considere que as costuras nos sentidosdas diagonais dessa colcha são perfeitamenteretilíneas.O retalho A da colcha, que tem o formato de umtriângulo, pode ser classificado quanto a seusângulos internos e lados, respectivamente,como",
            A: "acutângulo e equilátero.",
            B: 'obtusângulo e escaleno.',
            C: "obtusângulo e isósceles.",
            D: "retângulo e isósceles.",
            name: 'option5',
            position: '5°',
            img: "/MathFundProva2/Questão5.png",
        },
        {
            question: "A cor dos pelos nas cobaias é condicionada por uma série de fatores genéticos. Uma cobaiamarrom teve três ninhadas, cada uma com um macho diferente. O quadro seguinte mostra aconstituição de cada ninhada.",
            questionPart2: "Escolhendo um descendente marrom ao acaso, a probabilidade de ele ser da 2ª ninhada é",
            A: "2",
            B: '3',
            C: "4",
            D: "6",
            E: '0',
            name: 'option6',
            position: '6°',
            img: "/MathFundProva2/Questão6.png",
        },
        {
            question: "Paulo precisa localizar sua amiga Juliana, que está em alguma estação do metrô de São Paulo.Para isso, usará o mapa do metrô representado na figura. Juliana disse apenas que pegou o metrô na estação Portuguesa-Tietê no sentido Jabaquara e desceu na 3ª estação após a estação São Bento.",
            questionPart2: "Na figura, cada ponto branco próximo ao nome da estação indica a sua posição. A estação em que Juliana está é",
            A: "Luz.",
            B: 'Armênia.',
            C: "São Joaquim.",
            D: "Jardim São Paulo.",
            name: 'option7',
            position: '7°',
            img: "/MathFundProva2/Questão7.png",
        },
        {
            question: "Um torcedor, antes de acessar as instalações de um estádio, comprou uma bebida cujo vasilhame de vidro traz no seu rótulo a informação: “Conteúdo líquido: 320 mL”. Não podendo acessar o estádio com esse vasilhame, ele deverá passar toda a bebida para um copo descartável de plástico em que caiba todo o conteúdo." ,
            questionPart2: "Que capacidade mínima deverá ter o copo, em centímetro cúbico, para comportar todo o conteúdo descrito no rótulo?",
            A: "0,32",
            B: '3,20',
            C: "32,00",
            D: "320,00",
            name: 'option8',
            position: '8°',
           
        },
        {
            question: "Uma pessoa deseja comprar um notebook pela internet que custa R$ 1 200,00 e o frete para entrega, R$ 40,00. Ela pagará R$ 200,00 de entrada e o restante, incluindo o frete, em cinco parcelas iguais, sem juros.",
            questionPart2: "O valor de cada parcela, em real, será igual a",
            A: "208",
            B: '200',
            C: "248",
            D: "240",
            name: 'option9',
            position: '9°',
            
        },
        {
            question: "Um comerciante quer comprar peças de decoração, que custam 3 reais cada uma, para serem revendidas em uma feira de artesanato. Para transportar todas as peças até a feira, o comerciante terá um gasto de 50 reais. Considerando que ele revenda todas as peças, cada uma por 5 reais, o comerciante pretende obter, descontado o frete, um lucro de 250 reais.",
            questionPart2: "Para obter o lucro desejado, a quantidade de peças que o comerciante deverá comprar é",
            A: "60",
            B: '100',
            C: "125",
            D: "150",
            name: 'option10',
            position: '10°',
            
        },
        {
            question: "Quatro empresas apresentaram orçamentos para a festa de casamento de um casal, para 110 convidados, conforme as descrições seguintes:",
            questionPart2: "Esse casal escolheu a empresa que apresentou o menor orçamento. A escolhida foi a empresa",
            A: "I.",
            B: 'II.',
            C: "III.",
            D: "IV.",
            name: 'option11',
            position: '11°',
            img: "/MathFundProva2/Questão11.png",
            
        },
        {
            question: "Na construção civil existe uma grande variedade de materiais de acabamento. Em especial, na linha de cerâmica e porcelanato, diversas formas e modelos estão disponíveis no mercado. A figura mostra um ambiente que foi revestido com peças de porcelanato que, por terem a forma de um hexágono regular, encaixam-se perfeitamente em torno do ponto P. ",
            questionPart2: "A medida do ângulo interno do hexágono regular, que representa a peça de porcelanato na figura, é",
            A: "360°",
            B: '240°',
            C: "150°",
            D: "120°",
            name: 'option12',
            position: '12°',
            img: "/MathFundProva2/Questão12.png",
        },
        {
            question: "Cada um dos quatro vendedores que trabalham em uma revendedora de carros usados conseguiu, em determinado dia, comprar um carro e, logo em seguida, revendê-lo. O gráfico mostra os valores de compra e de venda negociados pelos quatro vendedores.",
            questionPart2: "Qual dos vendedores obteve o maior lucro entre a compra e a venda do carro negociado por ele?",
            A: "1",
            B: '2',
            C: "3",
            D: "4",
            name: 'option13',
            position: '13°',
            img: "/MathFundProva2/Questão13.png",
        },
        {
            question: "Uma pessoa pretende comprar um hambúrguer pagando-o por meio de um aplicativo de celular que lhe mostra quatro lojas diferentes que vendem o hambúrguer pretendido. Ela comprará na loja que oferecer o menor preço possível para esse hambúrguer. Sabe-se que, se o pagamento for efetuado em parcela única, os estabelecimentos oferecem um desconto no valor do pedido. O quadro mostra os estabelecimentos encontrados, os preços dos hambúrgueres e os respectivos percentuais de desconto.",
            questionPart2: "Em que estabelecimento a pessoa comprará o hambúrguer?",
            A: "I",
            B: 'II',
            C: "III",
            D: "IV",
            name: 'option14',
            position: '14°',
            img: "/MathFundProva2/Questão14.png",
        },
        {
            question: "Na banca de um determinado feirante encontram-se as seguintes placas de preços:",
            questionPart2: "Uma pessoa chegou à feira com R$ 25,00 e comprou, nessa banca, 2 kg de tomate, 4 kg de batata e 3 kg de cebola. Ela pretende gastar o restante do dinheiro comprando pimentão, mas reservando R$ 2,35 para pegar o ônibus de volta para casa. A quantidade de pimentão, em quilograma, que essa pessoa conseguirá comprar naquela banca é",
            A: "2,500.",
            B: '3,675.',
            C: "5,000.",
            D: "8,475.",
            name: 'option15',
            position: '15°',
            img: "/MathFundProva2/Questão15.png",
        },
        {
            question: "Uma mãe precisa administrar um remédio a seu filho, cuja massa corpórea é de 24 kg. A dosagem desse remédio é baseada na massa corpórea da criança. Esse remédio tem dosagem de 9 mL para crianças com até 5 kg de massa. Para indivíduos com mais de 5 kg de massa, a dosagem, em mililitro, é proporcional à massa corpórea, e o quadro a seguir apresenta as dosagens para algumas massas corpóreas.",
            questionPart2: "A dosagem desse remédio, em mililitro, que a mãe deverá dar ao seu filho é",
            A: "16",
            B: '36',
            C: "43",
            D: "45",
            name: 'option16',
            position: '16°',
            img: "/MathFundProva2/Questão16.png",
        },
        {
            question: "Uma pessoa contratou um jardineiro para cortar o gramado de sua residência. O tempo gasto por esse jardineiro para cortar a grama de uma região de 40 m² foi de 80 minutos. A figura representa o gramado, indicando as regiões onde o trabalho já foi realizado e onde o gramado ainda deve ser aparado.",
            questionPart2: "Considere que o jardineiro mantenha o mesmo ritmo de trabalho no restante do gramado. Quanto tempo, em minuto, o jardineiro levará para concluir o restante do corte do gramado?",
            A: "320",
            B: '200',
            C: "120",
            D: "100",
            name: 'option17',
            position: '17°',
            img: "/MathFundProva2/Questão17.png",
        },
        {
            question: "O sistema de venda de passagens numa empresa de ônibus associa a acomodação de um passageiro no ônibus de acordo com a ordem em que a passagem é vendida. Essa associação segue o seguinte padrão: o primeiro passageiro é associado ao assento 1A, o segundo, ao assento 1B, o terceiro, ao assento 1C, o quarto, ao assento 1D, o quinto, ao assento 2A, e assim sucessivamente. A imagem ilustra uma parte da distribuição dos assentos nos ônibus dessa empresa, os quais têm 12 fileiras horizontais.",
            questionPart2: "Um passageiro comprou a vigésima sétima passagem de um ônibus dessa empresa. Esse passageiro será associado ao assento",
            A: "2C",
            B: '3C',
            C: "6C",
            D: "7C",
            name: 'option18',
            position: '18°',
            img: "/MathFundProva2/Questão18.png",
        },
        {
            question: "Para ir à casa de seus avós, um menino gasta menos de duas horas utilizando uma linha de ônibus. Um dia, porém, um acidente no trajeto dessa linha de ônibus deixou o fluxo de veículos muito lento e o menino levou 2 1/2 horas para completar o mesmo trajeto.",
            questionPart2: "O número decimal correspondente ao tempo, em hora, que o menino gastou para completar o trajeto nesse dia foi",
            A: "0,5",
            B: '1,5',
            C: "2,0",
            D: "2,5",
            name: 'option19',
            position: '19°',
           
        },
        {
            question: "Um cliente recebeu sua fatura mensal do cartão de crédito no valor de R$ 2 500,00 mas não podia fazer o pagamento integral da fatura. Para quitação do débito de forma parcelada, a administradora do cartão de crédito ofereceu os seguintes planos de pagamento:",
            questionPart2: "A qual desses planos o cliente deve aderir para ter o menor gasto total com o pagamento dessa fatura?",
            A: "1",
            B: '2',
            C: "3",
            D: "4",
            name: 'option20',
            position: '20°',
            img: "/MathFundProva2/Questão20.png",
        
        },
        {
            question: "O dono de um automóvel bicombustível queria verificar qual combustível lhe proporcionaria menor gasto mensal, considerando que seus deslocamentos diários eram feitos sempre pelos mesmos trajetos. Em cada abastecimento, colocou a mesma quantidade de combustível e anotou o valor pago pelo abastecimento. Posteriormente, calculou a distância percorrida com aquela quantidade de combustível e construiu o seguinte quadro:",
            questionPart2: "O critério de rendimento utilizado por essa pessoa foi observar quanto ela gastava para percorrer cada quilômetro com seu carro, quando abastecido pelos diferentes tipos de combustíveis. Ordenando os combustíveis pelo seu critério de rendimento, do mais econômico para o menos econômico, o dono do automóvel obteve corretamente a sequência",
            A: "etanol – gasolina comum – gasolina aditivada",
            B: 'gasolina aditivada – gasolina comum – etanol.',
            C: "gasolina comum – etanol – gasolina aditivada.",
            D: "gasolina aditivada – etanol – gasolina comum.",
            name: 'option21',
            position: '21°',
            img: "/MathFundProva2/Questão21.png",
        },
        {
            question: "Uma pessoa tomou um determinado empréstimo e realizará o pagamento deste em 11 parcelas mensais, iguais e consecutivas, de R$ 1 000,00. Mas, após pagar 5 dessas parcelas, percebeu que essa despesa mensal correspondia a 40% de seu salário. Para reorganizar suas contas, só poderia arcar com uma parcela que correspondesse a 20%. O seu salário permanecerá igual até o término do empréstimo. Ao buscar renegociar o montante que ainda iria vencer, recebeu as seguintes propostas calculadas sob juros simples, incidindo sobre o valor que falta pagar e dividindo o pagamento a ser feito em parcelas iguais e consecutivas.",
            questionPart2: "A proposta que se enquadra na condição possível de pagamento dessa pessoa é a",
            A: "I.",
            B: 'II.',
            C: "III.",
            D: "IV.",
            name: 'option22',
            position: '22°',
            img: "/MathFundProva2/Questão22.png",
        },
        {
            question: "Para efetuar a medida de uma grandeza, precisamos estabelecer uma unidade de medida como referência para, a partir daí, definir o comprimento, a área, a massa ou o que se quer medir. ",
            questionPart2: "O personagem Caco, a fim de impressionar seu amigo, determinou a sua altura em um submúltiplo do metro, que é a unidade padrão no Sistema Internacional de Unidades para medir a grandeza comprimento. Pode-se considerar que ele não está sendo exagerado, pois a altura média de um animal adulto da sua espécie é de 1,50 m. Com base nessas informações, quantos centímetros devem ser somados à medida da altura de Caco para alcançar a média de altura de um animal adulto de sua espécie?",
            A: "70",
            B: '65',
            C: "7",
            D: "0,7",
            name: 'option23',
            position: '23°',
            img: "/MathFundProva2/Questão23.png",
        },
        {
            question: "Uma empresa realiza o transporte de mudanças intermunicipais. Para facilitar o trabalho dos funcionários na elaboração de orçamentos, disponibiliza um quadro que relaciona o preço a ser cobrado com a distância percorrida entre a coleta e a entrega dos objetos. O preço total a pagar (P) é composto por um valor proporcional à quantidade de quilômetros percorridos (d), acrescido de um valor fixo de R$ 400,00, referente ao carregamento e à descarga dos objetos.",
            questionPart2: "De acordo com as informações apresentadas no quadro, a expressão algébrica que relaciona o preço total a pagar (P) em função da quantidade de quilômetros percorridos, d, é",
            A: "P = 400 + 3d",
            B: 'P = 400 + 10d',
            C: "P = 400d + 3",
            D: "P = 3d + 10",
            name: 'option24',
            position: '24°',
            img: "/MathFundProva2/Questão24.png",
        },
        {
            question: "O corpo de bombeiros de uma cidade possui três hidrantes para combate a incêndios. A vazão de cada hidrante é apresentada na tabela.",
            questionPart2: "Em função do aumento do número de habitantes e considerando o histórico do número de atendimentos, o comandante do corpo de bombeiros julgou prudente dobrar a vazão total de água nos hidrantes para assegurar o sucesso das operações de combate aos incêndios. Para esse propósito, as vazões dos hidrantes A e B foram aumentadas ao máximo, para 80 L/min e 100 L/min, respectivamente. Para que a vazão de água dos três hidrantes juntos seja duplicada, a vazão, em litro por minuto, do hidrante C deve ser aumentada para",
            A: "220",
            B: '180',
            C: "130",
            D: "110",
            name: 'option25',
            position: '25°',
            img: "/MathFundProva2/Questão25.png",
        },
        {
            question: ".Em um colégio, para que o aluno seja aprovado, ele deve obter, como média aritmética simples das notas dos 4 bimestres, um valor igual ou superior a 60 pontos. Para compor a nota bimestral, são realizados dois trabalhos, cada um valendo T pontos, três provas, cada uma valendo P pontos, e um seminário valendo S pontos, totalizando 100 pontos essas seis avaliações. As notas obtidas por um aluno nos três primeiros bimestres estão indicadas no quadro.",
            questionPart2: "Esse aluno calculou a nota mínima necessária para que seja aprovado. A expressão algébrica que relaciona os valores a serem obtidos nas avaliações do 4º bimestre, de forma a garantir a nota mínima necessária para que esse aluno seja aprovado, é",
            A: "T + P + S = 60",
            B: '2T + 3P + S = 60',
            C: "2T + 3P + S = 80",
            D: "2T + 3P + S = 100",
            name: 'option26',
            position: '26°',
            img: "/MathFundProva2/Questão26.png",
        },
        {
            question: "Dois amigos, A e B, fizeram uma brincadeira: a cada número x, dito pelo amigo A, o amigo B respondia com um valor y, que seguia uma regra criada por ele. O objetivo da brincadeira era o amigo A descobrir a regra criada pelo amigo B. Os valores observados em cada rodada dessa brincadeira estão representados no quadro.",
            questionPart2: "A expressão que representa a regra criada pelo amigo B, a partir do número x, é igual a",
            A: "x + 3",
            B: '3x – 1',
            C: "x – 3",
            D: "3x + 1",
            name: 'option27',
            position: '27°',
            img: "/MathFundProva2/Questão27.png",
        },
        {
            question: "Em uma escola, foram comprados 120 m de tela. Toda essa tela deverá ser usada para cercar duas regiões quadradas: um galinheiro e uma horta. A fim de evitar que as aves comam as hortaliças, o galinheiro e a horta não terão fronteiras em comum. A direção da escola quer que a soma das áreas das duas regiões seja a maior possível, sendo que o lado do galinheiro deve medir, pelo menos, 14 m, enquanto o lado da horta deve medir, pelo menos, 13 m. ",
            questionPart2: "Suponha que, além disso, deseja-se que os comprimentos dos lados de ambas as regiões sejam números inteiros. Qual deverá ser a medida, em metro, do lado do galinheiro para se atingir esse objetivo?",
            A: "14",
            B: '15',
            C: "16",
            D: "17",
            name: 'option28',
            position: '28°',
           
        },
        {
            question: "Um jardineiro foi contratado para colocar grama em um terreno. No primeiro dia, ele colocou grama em metade do terreno, deixando o restante para fazer posteriormente. No segundo dia, chegou atrasado ao trabalho e colocou grama apenas na metade da parte que restou sem grama após o primeiro dia.",
            questionPart2: "A fração que representa a parte do terreno que ainda está sem grama após esses dois dias de trabalho é",
            A: "1/3",
            B: '2/3',
            C: "1/4",
            D: "3/4",
            name: 'option29',
            position: '29°',
           
        },
        {
            question: "A crise hídrica vivida recentemente no Brasil trouxe para as manchetes dos jornais os níveis dos reservatórios de água brasileiros. Nas imagens a seguir há uma ilustração do que são o volume útil e o volume morto de um reservatório de água, além dos níveis dos reservatórios que abastecem o estado do Rio de Janeiro, referentes ao dia 13 de agosto de 2015.",
            questionPart2: "O reservatório de Santa Branca tem capacidade para armazenar 438,5 bilhões de litros de água. O volume morto desse reservatório é de 131,2 bilhões de litros de água e representa 29,92% de sua capacidade. O volume útil de água disponível no reservatório Santa Branca, no dia 13 de agosto de 2015, em bilhões de litros, era mais próximo de",
            A: "9,83.",
            B: '43,10.',
            C: "122,15.",
            D: "174,30.",
            name: 'option30',
            position: '30°',
            img: "/MathFundProva2/Questão30.png",
        },
    
    ],
    MatematicaFundTeste2Gab: [

      { 
        name: "option1",
        value: "B",
    },
    {
      name : "option2",
      value: "B",
    },
    { value: "C",
     name: "option3"
    
},
    {value: "B",
    name: "option4"
},
    {value: "C",
    name: "option5"
},
    {value: "B",
    name: "option6"
},
    {value: "C",
    name: "option7"
},
    {value: "D",
    name: "option8"
},
    {value: "A",
    name: "option9"
},
    { value: "D",
    name: "option10"
},
    { value: "C",
    name: "option11"
},
    { value: "D",
    name: "option12"
    
},
    { value: "B",
    name: "option13"
    
},
    { value: "A",
    name: "option14"
    
},
    { value: "A",
    name: "option15"
    
},
    { value: "B",
    name: "option16"
    
},
    { value: "A",
    name: "option17"
    
},
    { value: "D",
    name: "option18"
    
},
    { value: "D",
    name: "option19"
    
},
    { value: "C",
    name: "option20"
    
},
    { value: "C",
    name: "option21"
    
},
    { value: "D",
    name: "option22"
    
},
    { value: "A",
    name: "option23"
    
},
    { value: "A",
    name: "option24"
    
},
    { value: "A",
    name: "option25"
    
},
    { value: "C",
    name: "option26"
    
},
    { value: "B",
    name: "option27"
    
},
    { value: "D",
    name: "option28"
    
},
    { value: "C",
    name: "option29"
    
},
    { value: "B",
    name: "option30"
    
},
    ],
    PortuguesFundTeste3: [
        {
            question: "",
            questionPart2: "No relato de sua experiência no garimpo, o narrador retrata uma realidade em que a",
            A: "disputa pelo ouro estimula a violência.",
            B: 'incerteza do sucesso leva ao alcoolismo.',
            C: "informalidade substitui a falta de professores.",
            D: "escassez do letramento afeta o convívio social.",
            name: 'option1',
            position: '1°',
            img: "/PortFundProva3/Questão1.png",
        },
        {
            question: "",
            questionPart2: "A percepção “impressionista” do eu lírico decorre da",
            A: "memória na reconstituição da infância.",
            B: 'valorização do pai graças ao trabalho.',
            C: "confusão entre fatos antigos e atuais.",
            D: "identidade entre a natureza e as cores.",
            name: 'option2',
            position: '2°',
            img: "/PortFundProva3/Questão2.png",
        },
        {
            question: "",
            questionPart2: "Coerente com os fatos narrados, o desfecho sintetiza um ponto de vista do narrador que se constrói a partir do",
            A: "conflito conjugal provocado pela rotina.",
            B: 'interesse masculino na partilha dos bens',
            C: "problema financeiro vivenciado pelo casal.",
            D: "comportamento desleixado de um dos cônjuges",
            name: 'option3',
            position: '3°',
            img: "/PortFundProva3/Questão3.png",
        },
        {
            question: "",
            questionPart2: "A importância social do cordel destacada no texto é seu poder de",
            A: "levar informação ao leitor.",
            B: 'assumir um papel didático.',
            C: "promover o entretenimento.",
            D: "comover com histórias de amor.",
            name: 'option4',
            position: '4°',
            img: "/PortFundProva3/Questão4.png",
        },
        {
            question: "",
            questionPart2: "Na imagem, a caracterização do personagem Carlitos é intensificada por meio do(a)",
            A: "figurino e da maquiagem cênica.",
            B: 'presença de um animal em cena.',
            C: "olhar lançado em direção à atriz.",
            D: "simplicidade dos objetos no cenário.",
            name: 'option5',
            position: '5°',
            img: "/PortFundProva3/Questão5.png",
        },
        {
            question: "",
            questionPart2: "A Figura 1 é uma fotografia do poeta Carlos Drummond de Andrade. A Figura 2 é um retrato desenhado do mesmo poeta, cuja forma de representação é denominada artisticamente de",
            A: "charge.",
            B: 'cartum.',
            C: "caricatura.",
            D: "reprodução.",
            name: 'option6',
            position: '6°',
            img: "/PortFundProva3/Questão6.png",
        },
        {
            question: "",
            questionPart2: "O texto teatral de Ariano Suassuna tem uma função moralizante, utilizada também pelos jesuítas durante a colonização do Brasil, com o propósito de",
            A: "destacar o papel da mulher na proteção da justiça.",
            B: 'solucionar a falta de confiança nas relações humanas.',
            C: "motivar o público a pedir além para garantir o desejado.",
            D: " ensinar as virtudes apreciadas pela sociedade em qualquer época.",
            name: 'option7',
            position: '7°',
            img: "/PortFundProva3/Questão7.png",
        },
        {
            question: "",
            questionPart2:"Considerando-se as diferenças entre jogo e esporte expostas no texto, um campeonato municipal de xadrez é um evento classificável como",
            A: "esporte, pois possui regras institucionalizadas",
            B: 'jogo, pois não requer esforço físico.',
            C: "modalidade esportiva, pois envolve mais de um participante.",
            D: "atividade lúdica, pois não prevê competitividade.",
            name: 'option8',
            position: '8°',
            img: "/PortFundProva3/Questão8.png",
        },
        {
            question: "",
            questionPart2: "O crescimento no número de academias no Brasil é decorrente do(a)",
            A: "custo acessível às diferentes classes sociais.",
            B: 'conscientização da população na busca por saúde.',
            C: "influência da mídia na valorização da estética corporal.",
            D: "carência de espaços públicos para a prática de atividades.",
            name: 'option9',
            position: '9°',
            img: "/PortFundProva3/Questão9.png",
        },
        {
            question: "",
            questionPart2: "A longa permanência de atletas do futebol feminino na Seleção brasileira, numa faixa etária considerada avançada para o esporte, ocorre devido à",
            A: "pouca competitividade nos campeonatos.",
            B: 'força do vínculo entre as atletas e a Seleção.',
            C: "capacidade de adaptação e resistência muscular.",
            D: "falta de incentivo para a modalidade.",
            name: 'option10',
            position: '10°',
            img: "/PortFundProva3/Questão10.png",
        },
        {
            question: "",
            questionPart2: "Os recursos verbais e não verbais indicam que o objetivo da charge é",
            A: "expor a disparidade do número de falantes das diferentes línguas.",
            B: 'exibir a realização de manifestações favoráveis a distintos idiomas.',
            C: "sinalizar que as diferentes línguas devem ser respeitadas.",
            D: "indicar que os distintos idiomas devem caminhar juntos.",
            name: 'option11',
            position: '11°',
            img: "/PortFundProva3/Questão11.png",
        },
        {
            question: "",
            questionPart2: "A história em quadrinhos aproxima os leitores de uma problemática acerca da inclusão social. Sua função consiste em",
            A: "enaltecer as capacidades cognitivas de pessoas com T.E.A.",
            B: 'apresentar informações para combater a discriminação contra autistas.',
            C: "empregar termo técnico para descrever o autismo.",
            D: "retratar as características de uma enfermidade.",
            name: 'option12',
            position: '12°',
            img: "/PortFundProva3/Questão12.png",
        },
        {
            question: "",
            questionPart2: "A palavra “colorful” é utilizada na quarta estrofe do poema como uma exaltação ao(à)",
            A: "globalização.",
            B: 'patriotismo.',
            C: "diversidade.",
            D: "companheirismo.",
            name: 'option13',
            position: '13°',
            img: "/PortFundProva3/Questão13.png",
        },
        {
            question: "",
            questionPart2: "Essa letra de canção é de Assis Valente, famoso compositor brasileiro do século passado, que já destacava o(a)",
            A: "emprego de palavras em inglês no cotidiano brasileiro.",
            B: 'importância da iluminação pública nas favelas.',
            C: "emigração de brasileiros para o exterior.",
            D: "educação dos moradores do morro.",
            name: 'option14',
            position: '14°',
            img: "/PortFundProva3/Questão14.png",
        },
        {
            question: "",
            questionPart2: "O cartaz da campanha de vacinação contra a paralisia infantil foi criado com a finalidade de",
            A: "divertir o público-alvo da campanha com a imagem do Zé Gotinha.",
            B: 'apresentar informações relevantes para o usufruto desse direito pela população.',
            C: "dar orientações a respeito das propriedades terapêuticas da vacina contra a paralisia.",
            D: "amenizar nas crianças o medo de receber a injeção com a vacina.",
            name: 'option15',
            position: '15°',
            img: "/PortFundProva3/Questão15.png",
        },
        {
            question: "",
            questionPart2: "A palavra “desempregado”, usada na charge, contém o prefixo “des-”, que apresenta vários sentidos implícitos. Nesse contexto, seu significado é o de:",
            A: "oposição.",
            B: 'separação.',
            C: "intensidade.",
            D: "afastamento.",
            name: 'option16',
            position: '16°',
            img: "/PortFundProva3/Questão16.png",
        },
        {
            question: "",
            questionPart2: "Nesse poema, é possível estabelecer referência a uma cantiga de roda tradicional na cultura brasileira. O verso que evidencia a relação entre o poema e a cantiga de roda é:",
            A: "“Atirei um limão n’água”.",
            B: '“Quem tem amor tem coragem”.',
            C: "“Nenhum peixe me avisou”.",
            D: "“Hás de amar eternamente”.",
            name: 'option17',
            position: '17°',
            img: "/PortFundProva3/Questão17.png",
        },
        {
            question: "",
            questionPart2: "Para tentar manter os níveis de arrecadação registrados nos últimos anos, a Campanha do Agasalho em questão utilizou um argumento verbal baseado na",
            A: "carência financeira dos necessitados.",
            B: 'compaixão humana pelos menos favorecidos.',
            C: "comparação entre um tipo de agasalho e a proteção por ele oferecida.",
            D: "repetição de um acontecimento da natureza e de um comportamento humano.",
            name: 'option18',
            position: '18°',
            img: "/PortFundProva3/Questão18.png",
        },
        {
            question: "",
            questionPart2: "A língua portuguesa manifesta a heterogeneidade social, regional e histórica de seu povo. As variedades linguísticas são a expressão dessa heterogeneidade. No uso linguístico feito na charge, identifica-se a variação",
            A: "social.",
            B: 'regional.',
            C: "etária.",
            D: "profissional.",
            name: 'option19',
            position: '19°',
            img: "/PortFundProva3/Questão19.png",
        },
        {
            question: "A professora escreve no quadro: (a + b)n. Depois, pede a Joãozinho que vá ao quadro e expanda a expressão. Ele obedece:",
            questionPart2: "A resposta de Joãozinho à solicitação da professora indica que ele relacionou a palavra “expanda” ao sentido de",
            A: "elevação.",
            B: 'dilatação.',
            C: "separação.",
            D: "reduplicação.",
            name: 'option20',
            position: '20°',
            img: "/PortFundProva3/Questão20.png",
        },
        {
            question: "",
            questionPart2: "Na tirinha, Beto Boleiro descreve como é sua rotina semanal. A partir do segundo quadrinho, o pronome “eu” foi omitido, pois as",
            A: "atividades descritas são corriqueiras na vida do leitor.",
            B: 'informações presentes nos verbos identificam quem fala.',
            C: "marcas de primeira pessoa são desnecessárias em metáforas sobre futebol.",
            D: "indicações de primeira pessoa são exclusivamente expressas por pronomes.",
            name: 'option21',
            position: '21°',
            img: "/PortFundProva3/Questão21.png",
        },
        {
            question: "",
            questionPart2: "Os exemplos citados no texto são empregados para mostrar que os super-heróis",
            A: "nascem de necessidades sociais.",
            B: 'despertam a imaginação infantil.',
            C: "promovem a união dos povos.",
            D: "revelam a alma humana.",
            name: 'option22',
            position: '22°',
            img: "/PortFundProva3/Questão22.png",
        },
        {
            question: "",
            questionPart2: "No texto, a expressão coloquial utilizada para aproximar-se do leitor fica evidenciada em",
            A: "“Escola é uma coisa”.",
            B: '“Estando ou não na escola”.',
            C: "“Investigue cada referência”.",
            D: "“Vá mais fundo”.",
            name: 'option23',
            position: '23°',
            img: "/PortFundProva3/Questão23.png",
        },
        {
            question: "",
            questionPart2: "Os recursos linguísticos empregados nesse texto o caracterizam como",
            A: "reportagem, pois discute um assunto apresentando detalhes.",
            B: 'notícia, pois revela informações recentes sobre um fato.',
            C: "declaração, pois comprova a entrega de um documento.",
            D: "manual, pois orienta como fazer a declaração.",
            name: 'option24',
            position: '24°',
            img: "/PortFundProva3/Questão24.png",
        },
        {
            question: "",
            questionPart2: "Como elementos que caracterizam esse cartum, as linguagens verbal e não verbal combinam-se para construir uma crítica ao(à)",
            A: "excesso de presentes dados às crianças.",
            B: 'valor do presente dado pelo avô ao menino.',
            C: "predileção das meninas por celulares em vez de games.",
            D: "preferência das crianças de hoje por brinquedos eletrônicos.",
            name: 'option25',
            position: '25°',
            img: "/PortFundProva3/Questão25.png",
        }, {
            question: "",
            questionPart2: "Integrante de um guia de orientação para os trabalhadores, o texto apresenta informações que",
            A: "orientam a respeito das garantias legais dos trabalhadores.",
            B: 'esclarecem sobre os impostos a serem recolhidos pelo patrão.',
            C: "denunciam casos de exploração trabalhista por empregadores.",
            D: "criticam as condições precárias a que são submetidos os trabalhadores.",
            name: 'option26',
            position: '26°',
            img: "/PortFundProva3/Questão26.png",
        },
        {
            question: "",
            questionPart2: "Crônica de autoria de um escritor indígena, o texto traz uma reflexão sobre o significado da palavra “Tatuapé”, que nomeia uma estação do metrô de São Paulo. Nessa reflexão, torna-se evidente que",
            A: "indígenas se ressentem do uso inapropriado da palavra “Tatuapé”.",
            B: 'palavras de origem indígena estão presentes no cotidiano brasileiro.',
            C: "brasileiros ignoram o sentido de palavras indígenas na língua portuguesa.",
            D: "sentidos da palavra “Tatuapé” são semelhantes para moradores da cidade e da floresta.",
            name: 'option27',
            position: '27°',
            img: "/PortFundProva3/Questão27.png",
        },
        {
            question: "",
            questionPart2: "Com o objetivo de combater a divulgação de notícias falsas, o texto estabelece diálogo com uma história do folclore. Essa referência é marcada pelo(a)",
            A: "uso da palavra “publicações”.",
            B: 'utilização da expressão “fonte”.',
            C: "emprego do símbolo de proibido.",
            D: "imagem de uma figura imaginária.",
            name: 'option28',
            position: '28°',
            img: "/PortFundProva3/Questão28.png",
        },
        {
            question: "",
            questionPart2: "Em relação ao Texto I, o Texto II estabelece um sentido de complementariedade ao",
            A: "detalhar aspectos sobre quem pode ser doador.",
            B: 'falar sobre a permissão da família para a doação.',
            C: "indicar que devemos informar a decisão aos familiares.",
            D: "mencionar o nome da campanha em que estão inseridos.",
            name: 'option29',
            position: '29°',
            img: "/PortFundProva3/Questão29.png",
        },
        {
            question: "",
            questionPart2: "A discussão proposta na crônica associa o uso do diminutivo e do aumentativo ao preconceito social. Essa afirmação evidencia-se no trecho",
            A: "“diminutivos e aumentativos têm conotações que expressam a brasilidade”.",
            B: '“os nomes de homem assumem diminutivos e se reportam exatamente a quando eram pequenos”.',
            C: "“Não faltam obras públicas feitas por mulheres da política”.",
            D: "“Faltam nomes delas, no aumentativo”.",
            name: 'option30',
            position: '30°',
            img: "/PortFundProva3/Questão30.png",
        },
    ],
    PortuguesFundTeste3Gab: [

        { 
          name: "option1",
          value: "D",
      },
      {
        name : "option2",
        value: "D",
      },
      { value: "D",
       name: "option3"
      
  },
      {value: "A",
      name: "option4"
  },
      {value: "A",
      name: "option5"
  },
      {value: "C",
      name: "option6"
  },
      {value: "D",
      name: "option7"
  },
      {value: "A",
      name: "option8"
  },
      {value: "C",
      name: "option9"
  },
      { value: "D",
      name: "option10"
  },
      { value: "C",
      name: "option11"
  },
      { value: "B",
      name: "option12"
      
  },
      { value: "C",
      name: "option13"
      
  },
      { value: "A",
      name: "option14"
      
  },
      { value: "B",
      name: "option15"
      
  },
      { value: "A",
      name: "option16"
      
  },
      { value: "A",
      name: "option17"
      
  },
      { value: "D",
      name: "option18"
      
  },
      { value: "B",
      name: "option19"
      
  },
      { value: "B",
      name: "option20"
      
  },
      { value: "B",
      name: "option21"
      
  },
      { value: "A",
      name: "option22"
      
  },
      { value: "D",
      name: "option23"
      
  },
      { value: "B",
      name: "option24"
      
  },
      { value: "D",
      name: "option25"
      
  },
      { value: "A",
      name: "option26"
      
  },
      { value: "B",
      name: "option27"
      
  },
      { value: "D",
      name: "option28"
      
  },
      { value: "A",
      name: "option29"
      
  },
      { value: "D",
      name: "option30"
      
  },
      ],
      HistoriaGeografiaFundTeste4: [
        {
            question: "",
            questionPart2: "De acordo com o mapa, a maior quantidade de trechos navegáveis do Brasil encontra-se na Região",
            A: "Norte.",
            B: 'Sudeste.',
            C: "Nordeste.",
            D: "Centro-Oeste.",
            name: 'option1',
            position: '1°',
            img: "/HistGeoProva4/Questão1.png",
        },
        {
            question: "",
            questionPart2: "A demolição ilustrada na imagem indica uma desvalorização do patrimônio cultural motivada pela",
            A: "ampliação do transporte coletivo.",
            B: 'diminuição do fluxo populacional.',
            C: "manutenção da paisagem urbana.",
            D: "expansão da especulação imobiliária.",
            name: 'option2',
            position: '2°',
            img: "/HistGeoProva4/Questão2.png",
        },
        {
            question: "",
            questionPart2: "Uma semelhança política entre essas duas potências estava baseada no(a)",
            A: "iberdade de expressão.",
            B: 'liberalismo econômico.',
            C: "personalismo das lideranças.",
            D: "representatividade do parlamento.",
            name: 'option3',
            position: '3°',
            img: "/HistGeoProva4/Questão3.png",
        },
        {
            question: "",
            questionPart2: "Os textos relatam os efeitos do processo de ocupação territorial brasileira, cujo reflexo foi o(a)",
            A: "enfraquecimento da cultura nativa.",
            B: 'manutenção da agricultura sustentável.',
            C: "valorização das populações tradicionais.",
            D: "fortalecimento das organizações econômicas.",
            name: 'option4',
            position: '4°',
            img: "/HistGeoProva4/Questão4.png",
        },
        {
            question: "",
            questionPart2: "Qual característica das religiões afro-brasileiras está exemplificada na letra da canção?",
            A: "Uso de amuletos da sorte.",
            B: 'Oferenda de alimentos sagrados.',
            C: "Crença na existência de deuses.",
            D: "Celebração com animais sacrificados.",
            name: 'option5',
            position: '5°',
            img: "/HistGeoProva4/Questão5.png",
        },
        {
            question: "",
            questionPart2: "O objetivo da Coroa Portuguesa ao incentivar o tipo de atividade retratada na imagem foi",
            A: "promover a rotação de culturas nas capitanias.",
            B: 'manter o abastecimento do consumo interno.',
            C: "estimular a ocupação territorial do interior.",
            D: "explorar o potencial lucrativo da colônia.",
            name: 'option6',
            position: '6°',
            img: "/HistGeoProva4/Questão6.png",
        },
        {
            question: "",
            questionPart2: "A vinda desses imigrantes para o Brasil, nos primeiros anos após a Proclamação da República, intensificou-se em virtude da",
            A: "abolição do trabalho escravo.",
            B: 'modernização do espaço urbano.',
            C: "legalização da mão de obra fabril.",
            D: "ampliação do transporte marítimo.",
            name: 'option7',
            position: '7°',
            img: "/HistGeoProva4/Questão7.png",
        },
        {
            question: "",
            questionPart2:"A análise do mapa indica que esta prova que você está fazendo começou com os relógios",
            A: "marcando a mesma hora em todo o Brasil.",
            B: 'marcando horas iguais em toda a Região Norte.',
            C: "no Acre indicando horário mais cedo do que em Goiás.",
            D: "em Minas Gerais indicando horário diferente do que no Ceará.",
            name: 'option8',
            position: '8°',
            img: "/HistGeoProva4/Questão8.png",
        },
        {
            question: "",
            questionPart2: "O avanço da fronteira agropecuária representado no gráfico é maior em qual região?",
            A: "Sul.",
            B: 'Nordeste.',
            C: "Sudeste.",
            D: "Norte.",
            name: 'option9',
            position: '9°',
            img: "/HistGeoProva4/Questão9.png",
        },
        {
            question: "",
            questionPart2: "O principal documento brasileiro que promove aos cidadãos os direitos mencionados na tirinha e no texto é o(a): ",
            A: "Código Florestal.",
            B: 'Estatuto da Cidade.',
            C: "Constituição Federal.",
            D: "Legislação de Trânsito.",
            name: 'option10',
            position: '10°',
            img: "/HistGeoProva4/Questão10.png",
        },
        {
            question: "",
            questionPart2: "A presença, no Brasil contemporâneo, da festividade descrita no texto reflete o(a)            ",
            A: "imposição das festas religiosas em todo país.",
            B: 'preservação de elementos da cultura lusitana.',
            C: "fortalecimento de uma nova tradição brasileira.",
            D: "legalização das manifestações culturais.",
            name: 'option11',
            position: '11°',
            img: "/HistGeoProva4/Questão11.png",
        },
        {
            question: "",
            questionPart2: "O texto trata de uma época de autoritarismo no Brasil, marcada pelo",
            A: "desaparecimento de presos políticos.",
            B: 'enfraquecimento da capacidade artística.',
            C: "aumento das garantias de direitos individuais.",
            D: "fortalecimento da atuação dos parlamentares eleitos.",
            name: 'option12',
            position: '12°',
            img: "/HistGeoProva4/Questão12.png",
        },
        {
            question: "",
            questionPart2: "A análise do texto e do gráfico demonstra que a fonte que mais influencia a matriz elétrica brasileira vem das",
            A: "bacias hidrográficas.",
            B: 'reservas petrolíferas.',
            C: "plantações agrícolas.",
            D: "explorações minerais.",
            name: 'option13',
            position: '13°',
            img: "/HistGeoProva4/Questão13.png",
        },
        {
            question: "",
            questionPart2: "O evento descrito no texto representa uma situação temporária de",
            A: "fragilização social.",
            B: 'inversão de papéis.',
            C: "exclusão econômica.",
            D: "exaltação da violência.",
            name: 'option14',
            position: '14°',
            img: "/HistGeoProva4/Questão14.png",
        },
        {
            question: "",
            questionPart2: "Qual medida vem intensificando o assoreamento destacado no texto?",
            A: "Melhoria nos solos.",
            B: 'Retirada da vegetação.',
            C: "Privatização dos portos.",
            D: "Diminuição na mineração.",
            name: 'option15',
            position: '15°',
            img: "/HistGeoProva4/Questão15.png",
        },
        {
            question: "",
            questionPart2: "O sítio arqueológico mencionado no texto deve ser preservado com o objetivo de manter viva a memória sobre o(s)",
            A: "controle técnico da marinha.",
            B: 'episódios trágicos da história.',
            C: "fluxo de viajantes estrangeiros.",
            D: "registros de atividades artesanais.",
            name: 'option16',
            position: '16°',
            img: "/HistGeoProva4/Questão16.png",
        },
        {
            question: "",
            questionPart2: "A frase do presidente Figueiredo foi dita durante o período de retorno do Brasil à democracia, em fins dos anos 1970. Apesar de pronunciada em favor da abertura política, o posicionamento de Figueiredo contrariava o ideal de democracia porque",
            A: "impunha o respeito às leis criadas pelos presidentes que o antecederam.",
            B: 'obrigava o cumprimento das leis pelo povo.',
            C: "apresentava o processo político como uma vontade pessoal.",
            D: "estimulava a mobilização e participação popular.",
            name: 'option17',
            position: '17°',
            img: "/HistGeoProva4/Questão17.png",
        },
        {
            question: "",
            questionPart2: "Apesar de diferentes, as duas instituições mencionadas nos textos propõem-se a",
            A: "resguardar a memória do país.",
            B: 'fortalecer o comércio da cidade.',
            C: "privatizar os arquivos de pesquisa.",
            D: "ampliar as áreas de reflorestamento.",
            name: 'option18',
            position: '18°',
            img: "/HistGeoProva4/Questão18.png",
        },
        {
            question: "",
            questionPart2: "O cotidiano das mulheres mencionado no texto é marcado pela",
            A: "valorização das tarefas manuais.",
            B: 'ampliação de atividades educativas.',
            C: "transformação das obrigações diárias.",
            D: "concentração de funções domésticas.",
            name: 'option19',
            position: '19°',
            img: "/HistGeoProva4/Questão19.png",
        },
        {
            question: "",
            questionPart2: "Na ação descrita, qual elemento foi usado para promover a integração entre os diferentes povos?",
            A: "Crença na religião.",
            B: 'Interesse pelo esporte.',
            C: "Fluência no idioma local.",
            D: "Aceitação pela classe social.",
            name: 'option20',
            position: '20°',
            img: "/HistGeoProva4/Questão20.png",
        },
        {
            question: "",
            questionPart2: "A comparação entre as imagens de dois momentos históricos do bairro da Lapa, no Rio de Janeiro, revela a seguinte transformação:",
            A: "Ampliação da área aterrada.",
            B: 'Redução do saneamento básico.',
            C: "Expansão das moradias populares.",
            D: "Retração das atividades industriais.",
            name: 'option21',
            position: '21°',
            img: "/HistGeoProva4/Questão21.png",
        },
        {
            question: "",
            questionPart2: "Qual problema social é evidenciado na imagem?",
            A: "Violência urbana.",
            B: 'Trabalho informal.',
            C: "Déficit habitacional.",
            D: "Poluição atmosférica.",
            name: 'option22',
            position: '22°',
            img: "/HistGeoProva4/Questão22.png",
        },
        {
            question: "",
            questionPart2: "A charge expressa que o conhecimento adquirido pelo aluno na sala de aula foi importante para compreender que campo e cidade são caracterizados pela relação de",
            A: "dominação.",
            B: 'complemento.',
            C: "subordinação.",
            D: "distanciamento.",
            name: 'option23',
            position: '23°',
            img: "/HistGeoProva4/Questão23.png",
        },
        {
            question: "",
            questionPart2: "Essas tradições, realizadas fora de seu lugar de origem, são resultado das migrações",
            A: "internas, que são feitas entre estados brasileiros.",
            B: 'pendulares, que são feitas entre cidades vizinhas.',
            C: "forçadas, que são realizadas por refugiados climáticos.",
            D: "sazonais, que são realizadas por trabalhadores temporários.",
            name: 'option24',
            position: '24°',
            img: "/HistGeoProva4/Questão24.png",
        },
        {
            question: "",
            questionPart2: "Uma alternativa de intervenção visando a solução para o problema evidenciado no mapa é a",
            A: "criação extensiva de gado.",
            B: 'introdução do cultivo de soja.',
            C: "implantação de parque tecnológico.",
            D: "exploração sustentável dos recursos naturais.",
            name: 'option25',
            position: '25°',
            img: "/HistGeoProva4/Questão25.png",
        }, {
            question: "",
            questionPart2: "No gráfico, a proporção da população que vive em favelas apresentou",
            A: "redução na África.",
            B: 'acréscimo na Ásia.',
            C: "aumento na América Latina.",
            D: "diminuição na América do Norte.",
            name: 'option26',
            position: '26°',
            img: "/HistGeoProva4/Questão26.png",
        },
        {
            question: "",
            questionPart2: "A situação retratada no quadro, da primeira metade do século XX, tem como causa socioeconômica a",
            A: "ampliação da agricultura familiar.",
            B: 'expansão de fluxos migratórios.',
            C: "concentração de renda.",
            D: "redução da natalidade.",
            name: 'option27',
            position: '27°',
            img: "/HistGeoProva4/Questão27.png",
        },
        {
            question: "",
            questionPart2: "A letra da canção, tema de uma telenovela brasileira exibida em 2012, representa as empregadas domésticas como indivíduos,",
            A: "sem engajamento na esfera cultural.",
            B: 'com participação em sindicato local.',
            C: "com expectativas de ascensão social.",
            D: "sem perspectiva de promoção salarial.",
            name: 'option28',
            position: '28°',
            img: "/HistGeoProva4/Questão28.png",
        },
        {
            question: "",
            questionPart2: "O discurso do líder do movimento negro nos Estados Unidos tinha por objetivo rejeitar o",
            A: "plano de políticas cotistas.",
            B: 'acordo de tolerância racial.',
            C: "projeto de ações afirmativas.",
            D: "sistema de segregação social.",
            name: 'option29',
            position: '29°',
            img: "/HistGeoProva4/Questão29.png",
        },
        {
            question: "",
            questionPart2: "A imagem apresenta uma estratégia que é utilizada por produtores rurais no Brasil com o objetivo de",
            A: "monitorar a área de cultivo.",
            B: 'expandir a criação de gado.',
            C: "dispersar os insetos da região.",
            D: "diversificar as espécies de plantas.",
            name: 'option30',
            position: '30°',
            img: "/HistGeoProva4/Questão30.png",
        },
    ],
    classesMedio: [
        { class: "Matemática",
        pdf: "https://drive.google.com/u/0/uc?id=1xog7al6WIlqOdfGP3acD7oY7pLaAVAvV&export=download",
        testLink: '/',
    }, {
        class: "Lingua Portuguesa",
        pdf :"https://drive.google.com/u/0/uc?id=1QP8aqhNuNtWWn5JnN4_SNCilXzhLG7B0&export=download",
        testLink: '/',
    },
    {
        class: "História e Geografia",
        pdf : "https://drive.google.com/u/0/uc?id=1UGTzItcToU-hdHL3eafLJN_q65c6mQaF&export=download",
        testLink: '/',
    },
    { class: "Ciências",
      pdf : "https://drive.google.com/u/0/uc?id=1nuowAkabqpbH10WP9GJ5HSUUFAOeOBqB&export=download",
      testLink: '/',
    }
    ]
}

export default classesData